[2025-09-17T05:30:34.267+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_stream_dag.stream_crypto_ticks scheduled__2025-09-17T05:29:00+00:00 [queued]>
[2025-09-17T05:30:34.365+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_stream_dag.stream_crypto_ticks scheduled__2025-09-17T05:29:00+00:00 [queued]>
[2025-09-17T05:30:34.367+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-17T05:30:34.546+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): stream_crypto_ticks> on 2025-09-17 05:29:00+00:00
[2025-09-17T05:30:34.659+0000] {standard_task_runner.py:60} INFO - Started process 982 to run task
[2025-09-17T05:30:34.744+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_stream_dag', 'stream_crypto_ticks', 'scheduled__2025-09-17T05:29:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/crypto_stream_dag.py', '--cfg-path', '/tmp/tmpzrobipj6']
[2025-09-17T05:30:34.788+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask stream_crypto_ticks
[2025-09-17T05:30:35.279+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_stream_dag.stream_crypto_ticks scheduled__2025-09-17T05:29:00+00:00 [running]> on host 5940dd694332
[2025-09-17T05:30:35.870+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ho' AIRFLOW_CTX_DAG_ID='crypto_stream_dag' AIRFLOW_CTX_TASK_ID='stream_crypto_ticks' AIRFLOW_CTX_EXECUTION_DATE='2025-09-17T05:29:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-17T05:29:00+00:00'
[2025-09-17T05:30:35.916+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2025-09-17T05:30:35.915+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2025-09-17T05:30:35.916+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2025-09-17T05:30:35.940+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2025-09-17T05:30:40.207+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-09-17T05:30:40.265+0000] {process_utils.py:131} INFO - Sending 15 to group 982. PIDs of all processes in the group: [982]
[2025-09-17T05:30:40.268+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 982
